
---
baseURL: "https://blakeashleyjr.com/"
languageCode: "en-us"
title: "Blake Ashley Jr. - My thoughts on life, work, and tech"
theme: "terminal-custom"


params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true

languages:
  en:
    languageName: English
    title: Blake Ashley Jr.
    subtitle: My thoughts on tech, work, and life
    keywords: 'tech, work, life'
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Blake Ashley Jr.
        logoHomeLink: /

    # menu:
    #   main:
    #   - identifier: about
    #     name: About
    #     url: /about



...